# Mapeamento das chaves do Strava
strava.client-id=${STRAVA_CLIENT_ID}
strava.client-secret=${STRAVA_CLIENT_SECRET}
strava.access-token=${STRAVA_ACCESS_TOKEN}
strava.refresh-token=${STRAVA_REFRESH_TOKEN}

# Configurações extras do Spring (útil para debug)
logging.level.jackson.stravafit=DEBUG