# Use pontos para bater com o @Value("${strava.client.id}")
strava.client.id=${STRAVA_CLIENT_ID}
strava.client.secret=${STRAVA_CLIENT_SECRET}
strava.access.token=${STRAVA_ACCESS_TOKEN}
strava.refresh.token=${STRAVA_REFRESH_TOKEN}

# Perfil do Atleta para Cálculo de Karvonen
atleta.hr-max=173
atleta.hr-resting=53

# Configurações extras do Spring (útil para debug)
logging.level.jackson.stravafit=DEBUG